import { Inter } from "next/font/google";
import "./globals.css";
import FooterSection from "./components/FooterSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark:bg-background">
      <head>
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css" />
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
